### PR TITLE
New command: `get-state`

### LINKED ISSUE #67: Create new command: get-state

### PR DESCRIPTION
**Pull request by Buckram123**
Closes #67

We have got new query method: `get_state`: https://github.com/CronCats/cw-croncat/pull/101

Removed `status`, since we have `get-status` command, or what's the purpose of it? @mikedotexe 
Should one return whole struct :
https://github.com/CronCats/cw-croncat/blob/4b4974f161ba616ff9656f15b4249f51bb96544d/packages/cw-croncat-core/src/types.rs#L62-L71
While the other only status? https://github.com/CronCats/cw-croncat/blob/4b4974f161ba616ff9656f15b4249f51bb96544d/packages/cw-croncat-core/src/types.rs#L65

### CODE REVIEW

**Comment by Buckram123** [comment]
> Removed `status`, since we have `get-status` command, or what's the purpose of it? @mikedotexe Should one return whole struct : https://github.com/CronCats/cw-croncat/blob/4b4974f161ba616ff9656f15b4249f51bb96544d/packages/cw-croncat-core/src/types.rs#L62-L71 While the other only status? https://github.com/CronCats/cw-croncat/blob/4b4974f161ba616ff9656f15b4249f51bb96544d/packages/cw-croncat-core/src/types.rs#L65

Checking this file again, led me to noticing 5 month old smiley from Trevor, hah
https://github.com/CronCats/cw-croncat/blob/4b4974f161ba616ff9656f15b4249f51bb96544d/packages/cw-croncat-core/src/types.rs#L74

Screenshot_20220922_195348

**Comment by TrevorJTClarke** [comment]
Sorry, late to the party -- Is this just needed for debugging?

Im not a fan of this being a top level command. It shouldnt be needed by agents most of the time, if ever.
Let's for sure just make it a secret command (not part of menu) or remove altogether. 
Contract state should be accessible by junod query or via javascript if needed.

**Comment by Buckram123** [comment]
> Im not a fan of this being a top level command. It shouldnt be needed by agents most of the time, if ever. 

Sure, I'll hide it behind feature

**Comment by Buckram123** [comment]
> Sure, I'll hide it behind feature

Done, it's ready for review

**Review by TrevorJTClarke — APPROVED** [review]

**Review by d3v3us — APPROVED** [review]

**Pull request merged**
